baseURL = "http://example.org/"
languageCode = "de-de"
title = "Münster Guru - Wochenend-Tipps"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Thomas Werner"
disqusShortname = "shortDisquis"
googleAnalytics = "UA-1XXXXXXX1-X"
[params.index]
  picture = "/images/author.jpg"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading'''
  alertbar = true