baseURL = "http://example.org/"
languageCode = "en-us"
title = "Freizeit-Kompass Münster"
theme = "mediumish-gohugo-theme"
#theme = "ananke"
summaryLength = 25
copyright = "John Doe - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
Paginate=20
[params]
  logo = "/images/logo.png"
  description ="Ausflugsideen für die ganze Familie"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Thomas Werner"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/intro.jpg"
  title = "Freizeit-Kompass Münster"
  subtitle = "Unternehmungs-Tipps gegen Langeweile an münsteraner Wochenenden"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### Wähle eine Kategorie:
'''
  alertbar = false

[params.social]
  github = "tomsrocket"

  twitter = "toms_rocket"

## Main Menu
[[menu.main]]
    name = "Ausflugsziele"
    weight = 100
    identifier = "Ausflugsziele"
    url = "/ausflugsziele"
[[menu.main]]
    name = "Blog"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Kategorien"
    weight = 100
    identifier = "tags"
    url = "/tags"    
[[menu.main]]
    name = "Impressum"
    identifier = "impressum"
    weight = 200
    url = "/static/impressum"

