baseURL = "http://example.org/"
languageCode = "en-us"
title = "Freizeit-Kompass M체nster"
theme = "mediumish-gohugo-theme"
#theme = "ananke"
summaryLength = 25
copyright = "John Doe - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
Paginate=20
[params]
  logo = "/images/logo.png"
  description ="Ausflugsideen f체r die ganze Familie"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Thomas Werner"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/intro.jpg"
  title = "Freizeit-Kompass M체nster"
  subtitle = "Unternehmungs-Tipps gegen Langeweile an (verregneten) Wochenenden"
  mdtext = '''
### W채hle eine Kategorie:
'''
  alertbar = false

[params.social]
  github = "tomsrocket"

  twitter = "toms_rocket"

## Main Menu
[[menu.main]]
    name = "Ausflugsziele"
    weight = 100
    identifier = "Ausflugsziele"
    url = "/posts"
[[menu.main]]
    name = "Blog"
    identifier = "about"
    weight = 200
    url = "/blog"
[[menu.main]]
    name = "Kategorien"
    weight = 100
    identifier = "tags"
    url = "/tags"    
[[menu.main]]
    name = "Impressum"
    identifier = "impressum"
    weight = 200
    url = "/static/impressum"

